<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Internship extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        
    }

    public function index(){
        $this->load->view('layouts/header');
        $this->load->view('layouts/index/internship');
        $this->load->view('layouts/footer');

    }

}

/* End of file Internship.php */
/* Location: ./application/controllers/Internship.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-15 10:30:20 */
/* http://harviacode.com */