<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Content_image_model extends CI_Model
{

    public $table = 'content_image';
    public $id = 'ID_IMAGE';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('content_image.*,content.*');
        $this->db->from($this->table);
        $this->db->join('content', 'content_image.ID_CONTENT = content.ID_CONTENT');
        return $this->db->get()->result();
    }

    function get_by_menu($menu){
        $this->db->select('content_image.*');
        $this->db->from($this->table);
        $this->db->join('content', 'content.ID_CONTENT = content_image.ID_CONTENT');
        $this->db->join('content_category', 'content_category.ID_CATEGORY = content.ID_CATEGORY');
        $this->db->join('menu', 'menu.id = content_category.ID_MENU');
        $this->db->where('menu.name', $menu);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_IMAGE', $q);
	$this->db->or_like('ID_CONTENT', $q);
	$this->db->or_like('IMAGE', $q);
	$this->db->or_like('THUMBNAIL', $q);
	$this->db->or_like('NAME_IMAGE', $q);
	$this->db->or_like('INFO', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_IMAGE', $q);
	$this->db->or_like('ID_CONTENT', $q);
	$this->db->or_like('IMAGE', $q);
	$this->db->or_like('THUMBNAIL', $q);
	$this->db->or_like('NAME_IMAGE', $q);
	$this->db->or_like('INFO', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Content_image_model.php */
/* Location: ./application/models/Content_image_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-28 12:32:02 */
/* http://harviacode.com */