<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Content_category_model extends CI_Model
{

    public $table = 'content_category';
    public $id = 'ID_CATEGORY';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_CATEGORY', $q);
        $this->db->or_like('ID_MENU', $q);
        $this->db->or_like('CATEGORY', $q);
        $this->db->or_like('INFORMATION_CATEGORY', $q);
        $this->db->or_like('ICON_CATEGORY', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_CATEGORY', $q);
        $this->db->or_like('ID_MENU', $q);
        $this->db->or_like('CATEGORY', $q);
        $this->db->or_like('INFORMATION_CATEGORY', $q);
        $this->db->or_like('ICON_CATEGORY', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function get_by_menu($menu=NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('menu','menu.id=content_category.ID_MENU');
        $this->db->like('menu.name', $menu);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Content_category_model.php */
/* Location: ./application/models/Content_category_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-27 08:18:34 */
/* http://harviacode.com */