<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Faq_question_model extends CI_Model
{

    public $table = 'faq_question';
    public $id = 'ID_QUESTION';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('faq_answer', 'faq_answer.ID_ANSWER=faq_question.ID_ANSWER');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('faq_answer', 'faq_answer.ID_ANSWER=faq_question.ID_ANSWER');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_QUESTION', $q);
    	$this->db->or_like('ID_ANSWER', $q);
    	$this->db->or_like('QUESTION', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_QUESTION', $q);
    	$this->db->or_like('ID_ANSWER', $q);
    	$this->db->or_like('QUESTION', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Faq_question_model.php */
/* Location: ./application/models/Faq_question_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-27 05:16:08 */
/* http://harviacode.com */