<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Internship_model extends CI_Model
{

    public $table = 'internship';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select("internship.*,internship_position.TITLE");
        $this->db->order_by($this->id, $this->order);
        $this->db->join("internship_position","internship_position.id=internship.id_position");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select("internship.*,internship_position.TITLE");
        $this->db->where("internship.ID", $id);
        $this->db->join("internship_position","internship_position.id=internship.id_position");
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('ID', $q);
	$this->db->or_like('NAME', $q);
	$this->db->or_like('UNIVERSITY', $q);
	$this->db->or_like('SKILL', $q);
	$this->db->or_like('EMAIL', $q);
	$this->db->or_like('PHONE', $q);
	$this->db->or_like('MOTIVATION', $q);
	$this->db->or_like('ID_POSITION', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('ID', $q);
	$this->db->or_like('NAME', $q);
	$this->db->or_like('UNIVERSITY', $q);
	$this->db->or_like('SKILL', $q);
	$this->db->or_like('EMAIL', $q);
	$this->db->or_like('PHONE', $q);
	$this->db->or_like('MOTIVATION', $q);
	$this->db->or_like('ID_POSITION', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Internship_model.php */
/* Location: ./application/models/Internship_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-08-12 06:42:39 */
/* http://harviacode.com */